name: Deploy to Firebase Hosting

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: prodialer_app/admin-panel/package-lock.json

    - name: Install dependencies
      run: |
        cd prodialer_app/admin-panel
        npm ci

    - name: Build React app
      run: |
        cd prodialer_app/admin-panel
        npm run build

    - name: Use Node.js 20 for deploy step
      run: |
        sudo npm cache clean -f
        sudo npm install -g n
        sudo n 20
        node -v

    - name: Deploy to Firebase
      uses: FirebaseExtended/action-hosting-deploy@v0
      with:
        repoToken: '${{ secrets.GITHUB_TOKEN }}'
        firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
        channelId: live
        projectId: autocaller-91bb8
        entryPoint: ./prodialer_app 